export enum PermissionsEnum {
	// User
	LIST_USER = "LIST_USER",
	VIEW_USER = "VIEW_USER",
	CREATE_USER = "CREATE_USER",
	UPDATE_USER = "UPDATE_USER",
	DELETE_USER = "DELETE_USER",

	// Platform Categories
	LIST_PLATFORM_CATEGORY = "LIST_PLATFORM_CATEGORY",
	VIEW_PLATFORM_CATEGORY = "VIEW_PLATFORM_CATEGORY",
	CREATE_PLATFORM_CATEGORY = "CREATE_PLATFORM_CATEGORY",
	UPDATE_PLATFORM_CATEGORY = "UPDATE_PLATFORM_CATEGORY",
	DELETE_PLATFORM_CATEGORY = "DELETE_PLATFORM_CATEGORY",

	// Platform
	LIST_PLATFORM = "LIST_PLATFORM",
	VIEW_PLATFORM = "VIEW_PLATFORM",
	CREATE_PLATFORM = "CREATE_PLATFORM",
	UPDATE_PLATFORM = "UPDATE_PLATFORM",
	DELETE_PLATFORM = "DELETE_PLATFORM",

	// Custom Platform
	LIST_CUSTOM_PLATFORM = "LIST_CUSTOM_PLATFORM",
	VIEW_CUSTOM_PLATFORM = "VIEW_CUSTOM_PLATFORM",
	CREATE_CUSTOM_PLATFORM = "CREATE_CUSTOM_PLATFORM",
	UPDATE_CUSTOM_PLATFORM = "UPDATE_CUSTOM_PLATFORM",
	DELETE_CUSTOM_PLATFORM = "DELETE_CUSTOM_PLATFORM",

	// Roles
	LIST_ROLE = "LIST_ROLE",
	VIEW_ROLE = "VIEW_ROLE",
	CREATE_ROLE = "CREATE_ROLE",
	UPDATE_ROLE = "UPDATE_ROLE",
	DELETE_ROLE = "DELETE_ROLE",

	// Permissions
	LIST_PERMISSION = "LIST_PERMISSION",
	VIEW_PERMISSION = "VIEW_PERMISSION",

	LIST_USER_PROFILE = "LIST_USER_PROFILE",
	VIEW_USER_PROFILE = "VIEW_USER_PROFILE",
	CREATE_USER_PROFILE = "CREATE_USER_PROFILE",
	UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE",
	DELETE_USER_PROFILE = "DELETE_USER_PROFILE",
}
