export enum Industry {
	Technology = "Technology",
	Healthcare = "Healthcare",
	Education = "Education",
	Finance = "Finance",
	Retail = "Retail",
	Manufacturing = "Manufacturing",
	Automotive = "Automotive",
	Entertainment = "Entertainment",
	FoodAndBeverage = "Food & Beverage",
	TravelAndTourism = "Travel & Tourism",
	RealEstate = "Real Estate",
	FashionAndApparel = "Fashion & Apparel",
	EnergyAndUtilities = "Energy & Utilities",
	Construction = "Construction",
	MediaAndCommunication = "Media & Communication",
	Agriculture = "Agriculture",
	TransportationAndLogistics = "Transportation & Logistics",
	Hospitality = "Hospitality",
	LegalServices = "Legal Services",
	NonProfitAndPhilanthropy = "Non-profit & Philanthropy",
}
